In [1]:
import pymysql

In [2]:
# 远程服务器数据库配置
MYSQL_HOST = '192.144.239.176'
MYSQL_DBNAME = 'db'
MYSQL_USER = 'root'
MYSQL_PASSWD = '2F5gMs4jIabeFuOB'
MYSQL_PORT = 3306

# 连接到远程数据库
mydatabase = pymysql.connect(
    host=MYSQL_HOST,
    port=3306,
    db=MYSQL_DBNAME,
    user=MYSQL_USER,
    passwd=MYSQL_PASSWD,
    charset='utf8',
    use_unicode=True
)

In [3]:
cursor = mydatabase.cursor()
cursor.execute("select id, name from museum")
museums = cursor.fetchall()

cursor.close()

In [9]:
museums

((1, '故宫博物院'),
 (2, '中国科学技术馆'),
 (3, '中国地质博物馆'),
 (4, '中国人民革命军事博物馆'),
 (5, '中国航空博物馆'),
 (6, '北京鲁迅博物馆'),
 (7, '首都博物馆'),
 (8, '北京自然博物馆'),
 (9, '中国人民抗日战争纪念馆'),
 (10, '周口店猿人遗址博物馆'),
 (11, '中国国家博物馆'),
 (12, '中国农业博物馆'),
 (13, '北京天文馆'),
 (14, '文化部恭王府博物馆'),
 (15, '天津博物馆'),
 (16, '天津自然博物馆'),
 (17, '周恩来邓颖超纪念馆'),
 (18, '河北博物院'),
 (19, '西柏坡纪念馆'),
 (20, '邯郸市博物馆'),
 (21, '山西博物院'),
 (22, '中国煤炭博物馆'),
 (23, '八路军太行纪念馆'),
 (24, '内蒙古博物院'),
 (25, '鄂尔多斯博物馆'),
 (26, '辽宁省博物馆'),
 (27, '“九·一八”历史博物馆'),
 (28, '旅顺博物馆'),
 (29, '沈阳故宫博物院'),
 (30, '吉林省自然博物馆'),
 (31, '吉林省博物院'),
 (32, '伪满皇宫博物院'),
 (33, '东北烈士纪念馆'),
 (34, '铁人王进喜纪念馆'),
 (35, '爱辉历史陈列馆'),
 (36, '黑龙江省博物馆'),
 (37, '大庆博物馆'),
 (38, '上海博物馆'),
 (39, '上海鲁迅纪念馆'),
 (40, '中共一大会址纪念馆'),
 (41, '上海科技馆'),
 (42, '陈云纪念馆'),
 (43, '南京博物院'),
 (44, '侵华日军南京大屠杀遇难同胞纪念馆'),
 (45, '南通博物苑'),
 (46, '苏州博物馆'),
 (47, '扬州博物馆'),
 (48, '常州博物馆'),
 (49, '南京市博物总馆'),
 (50, '浙江省博物馆'),
 (51, '浙江自然博物院'),
 (52, '中国丝绸博物馆'),
 (53, '宁波博物馆'),
 (54, '杭州博物馆'),
 (55, '温州博物馆'),
 (56, '安徽博物院'),
 (57, '安徽中国徽州文化博物馆'),
 (58, '福建博物院'),
 (59, '古田会议纪念馆'),
 (60, '泉州海外交通史博物馆'),
 (61, '中国闽台缘博物馆'),
 (62, '中央苏区（闽西）历史博物馆'),
 (63, '井冈山革命博物馆'),
 (64, '江西省博物馆'),
 (65, '瑞金中央革命根据地纪念馆'),
 (66, '南昌八一起义纪念馆'),
 (67, '安源路矿工人运动纪念馆'),
 (68, '青岛市博物馆'),
 (69, '中国甲午战争博物馆'),
 (70, '青州博物馆'),
 (71, '山东博物馆'),
 (72, '烟台市博物馆'),
 (73, '潍坊市博物馆'),
 (74, '河南博物院'),
 (75, '郑州博物馆 （嵩山南路馆区）'),
 (76, '洛阳博物馆'),
 (77, '南阳汉画馆'),
 (78, '开封市博物馆'),
 (79, '鄂豫皖苏区首府革命博物馆'),
 (80, '湖北省博物馆'),
 (81, '荆州博物馆'),
 (82, '武汉博物馆'),
 (83, '辛亥革命武昌起义纪念馆'),
 (84, '湖南省博物馆'),
 (85, '韶山毛泽东故居纪念馆'),
 (86, '刘少奇故居纪念馆'),
 (87, '长沙简牍博物馆'),
 (88, '广东省博物馆'),
 (89, '西汉南越王博物馆'),
 (90, '孙中山故居纪念馆'),
 (91, '深圳博物馆'),
 (92, '广州博物馆'),
 (93, '广东民间工艺博物馆'),
 (94, '广西壮族自治区博物馆'),
 (95, '广西民族博物馆'),
 (96, '海南省博物馆'),
 (97, '自贡恐龙博物馆'),
 (98, '三星堆博物馆'),
 (99, '成都武侯祠博物馆'),
 (100, '邓小平故居陈列馆'),
 (101, '成都杜甫草堂博物馆'),
 (102, '四川博物院'),
 (103, '成都金沙遗址博物馆'),
 (104, '自贡市盐业历史博物馆'),
 (105, '遵义会议纪念馆'),
 (106, '云南省博物馆'),
 (107, '云南民族博物馆'),
 (108, '重庆中国三峡博物馆'),
 (109, '重庆红岩革命历史博物馆'),
 (110, '重庆自然博物馆'),
 (111, '西藏博物馆'),
 (112, '陕西历史博物馆'),
 (113, '秦始皇兵马俑博物馆'),
 (114, '延安革命纪念馆'),
 (115, '汉阳陵博物馆'),
 (116, '西安碑林博物馆'),
 (117, '西安半坡博物馆'),
 (118, '西安博物院'),
 (119, '宝鸡青铜器博物院'),
 (120, '西安大唐西市博物馆'),
 (121, '甘肃省博物馆'),
 (122, '天水市博物馆'),
 (123, '敦煌研究院'),
 (124, '固原博物馆'),
 (125, '宁夏博物馆'),
 (126, '青海省博物馆'),
 (127, '新疆维吾尔自治区博物馆'),
 (128, '吐鲁番博物馆'))

In [15]:
# 远程服务器数据库配置
MYSQL_HOST = '192.144.239.176'
MYSQL_DBNAME = 'db'
MYSQL_USER = 'root'
MYSQL_PASSWD = '2F5gMs4jIabeFuOB'
MYSQL_PORT = 3306

# 连接到远程数据库
mydatabase = pymysql.connect(
    host=MYSQL_HOST,
    port=3306,
    db=MYSQL_DBNAME,
    user=MYSQL_USER,
    passwd=MYSQL_PASSWD,
    charset='utf8',
    use_unicode=True
)

content = "在广州博物馆下属分馆“三·二九”起义指挥部旧址纪念馆展出"

# 从文章中寻找是否提到了与某些博物馆有关的某些关系
for museum_id, museum_name in museums:
    if museum_name in content:
        print(museum_name)
        sql = "select id from museum where name = '{0}'".format(museum_name)
        print(sql)
        cursor = mydatabase.cursor()
        cursor.execute(sql)
        museum = cursor.fetchall()
        new_id = 515
        print("insert into museum_has_new (museum_id, new_id) values ({0}, {1})".format(museum[0][0], new_id))
        try:
            cursor.execute("insert into museum_has_new (museum_id, new_id) values ({0}, {1})".format(museum[0][0], new_id))
            mydatabase.commit()
        except:
            mydatabase.rollback()
        cursor.close()

广州博物馆
select id from museum where name = '广州博物馆'
insert into museum_has_new (museum_id, new_id) values (92, 515)